# Purpose: Testing build, addons
#
# Author: "rob dux" <robwdux@gmail.com>
#
# https://docs.docker.com/compose/
# https://docs.docker.com/compose/compose-file/
#
# docker-compose -f <filename> build

version: '2'
services:
  init-test:
    extends:
      file: docker-compose.yml
      service: init
    image: robwdux/init:test
    build:
      args:
        ADD_CONSUL_TEMPLATE: 'true'
        ADD_TELEGRAF: 'true'
